project: producer

spring:
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
  mvc:
    view:
      prefix: /static/
    static-path-pattern: /static/**
    show-sql: false

server:
  port: 8099
  servlet:
    context-path: /${project}
  tomcat:
    uri-encoding: utf-8

dubbo:
  application:
    name: producer
  registry:
    #无注册中心的配置
#    address: N/A
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  #    accesslog: true
  scan:
    base-packages: com.steer.producer.service.impl

